name: YAML Lint and Component Publish

on:
  push:
    paths:
      - 'sample/a_common1/**/*.yaml'
      - 'sample/c_common1/**/*.yml'

jobs:
  lint-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Get changed YAML files
        id: get_changed_files
        run: |
          # Get list of changed .yaml and .yml files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.ya?ml$')
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run YAML lint on changed files
        if: env.changed_files != ''
        run: |
          # Run yamllint only on changed files
          yamllint ${{ env.changed_files }}
        continue-on-error: true
        id: yaml-lint

      - name: Check YAML lint result
        if: steps.yaml-lint.outcome == 'failure'
        run: |
          echo "YAML lint check failed. Stopping the workflow."
          exit 1

      - name: Publish new component (to staging)
        if: steps.yaml-lint.outcome == 'success'
        run: |
          echo 'ok'
